# Generated by Django 5.1.1 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('thumbnail_url', models.FileField(upload_to='media/thumbnail/')),
                ('video_file', models.FileField(upload_to='media/video/')),
                ('published_at', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
