# Generated by Django 5.1.1 on 2025-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_videos_alter_video_author_alter_video_published_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='thumbnail_url',
            new_name='thumbnail_image',
        ),
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
