# Generated by Django 5.1.1 on 2025-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_thumbnail_url_videos_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
