# Generated by Django 5.1.1 on 2025-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_videos_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
