# Generated by Django 4.2.24 on 2025-09-16 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_alter_video_published_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComments',
            new_name='YoutubeComment',
        ),
    ]
