# Generated by Django 4.2.24 on 2025-09-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_uploadcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcomment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.videos'),
        ),
        migrations.AlterField(
            model_name='youtubecomment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.video'),
        ),
    ]
