# Generated by Django 4.2.24 on 2025-09-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_uploadcomment_video_alter_youtubecomment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
