# Generated by Django 4.2.24 on 2025-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_videos_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='download',
            field=models.CharField(default='False'),
        ),
    ]
