# Generated by Django 4.2.24 on 2025-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_videos_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='download',
            field=models.BooleanField(default=False),
        ),
    ]
